### ISSUE TITLE
Please provide a checkbox to 'Ignore SSL errors' for downloading / uploading

### ISSUE THREAD

**Issue by skyscooby** [jenkinsci/artifact-promotion-plugin#10]
Promoting fails when using self signed SSL certificates (common in corporate Intranets). Maven has options to ignore these errors but I couldn't find options for this plugin in the System Configuration.

``sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Promotion could not be executed
org.jenkinsci.plugins.artifactpromotion.exception.PromotionException: Could not fetch artifacts for promotion
	at org.jenkinsci.plugins.artifactpromotion.NexusOSSPromoterClosure.promote(NexusOSSPromoterClosure.java:83)
	at org.jenkinsci.plugins.artifactpromotion.RemotePromoter.call(RemotePromoter.java:34)
	at org.jenkinsci.plugins.artifactpromotion.RemotePromoter.call(RemotePromoter.java:14)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at org.jenkinsci.plugins.artifactpromotion.NexusOSSPromotor.callPromotor(NexusOSSPromotor.java:62)
	at org.jenkinsci.plugins.artifactpromotion.ArtifactPromotionBuilder.perform(ArtifactPromotionBuilder.java:233)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Promotion could not be executed: Could not fetch artifacts for promotion``

**Comment by hcguersoy** [comment]
Hi @skyscooby ,

i'll check this if we could do it with the used library.
