### ISSUE TITLE
Promotion for Nexus 3?

### ISSUE THREAD

**Issue by D0rmouse** [jenkinsci/artifact-promotion-plugin#28]
I'm using the artifact-promotion-plugin sucessfully for a Nexus 2 promotion, but for Nexus 3 somehow it doesn't work.
Could it be that Nexus 3 isn't supported?

This is the error I get:

```
2020-07-10 09:49:32.759  [Pipeline] artifactPromotion
2020-07-10 09:49:32.813  Promotion could not be executed
2020-07-10 09:49:32.813  org.jenkinsci.plugins.artifactpromotion.exception.PromotionException: Could not deploy artifacts to release repository
2020-07-10 09:49:32.813  	at org.jenkinsci.plugins.artifactpromotion.NexusOSSPromoterClosure.promote(NexusOSSPromoterClosure.java:114)
2020-07-10 09:49:32.813  	at org.jenkinsci.plugins.artifactpromotion.RemotePromoter.call(RemotePromoter.java:57)
2020-07-10 09:49:32.813  	at org.jenkinsci.plugins.artifactpromotion.RemotePromoter.call(RemotePromoter.java:37)
2020-07-10 09:49:32.813  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
2020-07-10 09:49:32.813  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
2020-07-10 09:49:32.813  	at hudson.remoting.Request$2.run(Request.java:369)
2020-07-10 09:49:32.813  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
2020-07-10 09:49:32.813  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-10 09:49:32.813  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-07-10 09:49:32.813  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-07-10 09:49:32.813  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
2020-07-10 09:49:32.813  	at java.lang.Thread.run(Thread.java:748)
2020-07-10 09:49:32.815  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ***********
2020-07-10 09:49:32.815  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
2020-07-10 09:49:32.815  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
2020-07-10 09:49:32.815  		at hudson.remoting.Channel.call(Channel.java:955)
2020-07-10 09:49:32.815  		at org.jenkinsci.plugins.artifactpromotion.NexusOSSPromotor.callPromotor(NexusOSSPromotor.java:63)
2020-07-10 09:49:32.815  		at org.jenkinsci.plugins.artifactpromotion.ArtifactPromotionHelper.perform(ArtifactPromotionHelper.java:199)
2020-07-10 09:49:32.815  		at org.jenkinsci.plugins.artifactpromotion.ArtifactPromotionStep$ArtifactPromotionExecution.run(ArtifactPromotionStep.java:108)
2020-07-10 09:49:32.815  		at org.jenkinsci.plugins.artifactpromotion.ArtifactPromotionStep$ArtifactPromotionExecution.run(ArtifactPromotionStep.java:86)
2020-07-10 09:49:32.815  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
2020-07-10 09:49:32.815  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-07-10 09:49:32.815  		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-10 09:49:32.815  		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-07-10 09:49:32.815  		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-07-10 09:49:32.815  		... 1 more
2020-07-10 09:49:32.815  Promotion could not be executed: Could not deploy artifacts to release repository
```

**Comment by D0rmouse** [comment]
Created a smaller project which works with Nexus 3, so I'm closing.

**Comment by hcguersoy** [comment]
Just for the records, as stated in the README Nexus 3 is not supported as they have broken the WS API.
